# Numpy

In [173]:
import numpy as np

In [174]:
np.__version__

'1.26.4'

# Creating Array

In [175]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [176]:
type(my_list)

list

converting list to array

In [177]:
arr = np.array(my_list)

In [178]:
arr

array([0, 1, 2, 3, 4, 5])

In [179]:
type(arr)

numpy.ndarray

In [180]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [181]:
np.arange(3.0)

array([0., 1., 2.])

In [182]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [184]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [185]:
np.arange(20,10)

array([], dtype=int32)

In [186]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [187]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [188]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [189]:
np.arange(30,20)

array([], dtype=int32)

In [190]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [191]:
np.arange(10,10)

array([], dtype=int32)

In [192]:
np.arange()

TypeError: arange() requires stop to be specified.

In [21]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [22]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [25]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [26]:
zero = np.zeros((2,2),dtype=int)
print(zero)
print(type(zero))

[[0 0]
 [0 0]]
<class 'numpy.ndarray'>


In [27]:
zero = np.zeros((3,3),dtype=int)
zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [29]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.ones(3)

array([1., 1., 1.])

In [31]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [ ]:
np.ones(n)

NameError: name 'n' is not defined

In [33]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [35]:
rand(1,10)

NameError: name 'rand' is not defined

In [ ]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [37]:
np.random.rand(5)

array([0.17713972, 0.93975863, 0.59768865, 0.95561457, 0.25989067])

In [ ]:
np.rand(2)

AttributeError: module 'numpy' has no attribute 'rand'

In [39]:
np.random.rand(2,4)

array([[0.16828183, 0.98243081, 0.31774701, 0.96272456],
       [0.20658536, 0.48494851, 0.6163994 , 0.31152113]])

In [40]:
np.random.randint(2,4)

3

In [41]:
np.random.randint(2,20)

14

In [42]:
np.random.randint(0,1)

0

Random five numbers from 10to 20

In [43]:
np.random.randint(10,20,5)

array([13, 10, 19, 10, 11])

In [44]:
b = np.random.randint(10,20,5)
b

array([16, 10, 16, 19, 17])

In [45]:
import numpy as np


In [46]:
np.arange(1,13).reshape(3,4)



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [48]:
np.arange(1,13).reshape(6,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [49]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [50]:
b = np.random.randint(1, 100,(5,4))
b

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

In [51]:
type(b)

numpy.ndarray

In [52]:
b

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

In [53]:
b[:]

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

when we done slicing without giving any number all rows and column will be printedd.

In [54]:
b[1:3]

array([[97, 76, 10, 69],
       [58, 24, 17, 78]])

this will print  the rows from 1 row to (3-1) 2 row

In [55]:
b

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

In [56]:
b[1,2]

10

When we use comma this will print the 3rd number of 1st row.

In [57]:
b

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

In [58]:
b[1,3]

69

In [59]:
b[1,-1]

69

In [60]:
b

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

In [61]:
b[2:3]

array([[58, 24, 17, 78]])

In [62]:
b

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

In [63]:
b[0:-2]

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78]])

In [64]:
b

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

In [65]:
b[0,2]

61

In [66]:
b

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

In [67]:
b[-5,-3]

73

In [68]:
b

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

In [69]:
b[-4,2]

10

In [70]:
b

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

In [71]:
b[-4,-2]

10

In [72]:
b[:]

array([[73, 73, 61, 32],
       [97, 76, 10, 69],
       [58, 24, 17, 78],
       [35, 57, 39, 97],
       [27, 10, 47, 54]])

# Operations

In [73]:
a = np.random.randint(10,20,10)
a

array([11, 13, 16, 13, 12, 18, 18, 17, 15, 19])

In [74]:
id(a)

2588435243792

In [75]:
arr

array([0, 1, 2, 3, 4, 5])

In [76]:
arr2 = np.random.randint(0,100,(10,10))

In [77]:
arr2

array([[40, 19,  5, 43, 56, 64,  8, 25, 82, 94],
       [34, 95, 52, 24,  0,  6,  4, 27, 46, 67],
       [50, 79, 90, 30, 49, 85, 41, 90, 97, 55],
       [13, 96, 66, 33, 95, 43, 61, 22, 42, 96],
       [24, 90, 57, 95, 90, 67, 95, 67,  4, 45],
       [84, 32, 49, 31, 16, 14, 68, 86, 30, 25],
       [ 6, 10, 82,  7, 17, 70,  4, 50, 85, 58],
       [28, 45, 43,  0, 17,  0, 25, 53, 19, 17],
       [ 5, 67, 88,  9,  4, 48, 89, 75,  2, 60],
       [34, 30, 88, 48,  8, 84, 84, 99, 69, 90]])

In [78]:
arr

array([0, 1, 2, 3, 4, 5])

In [79]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [80]:
arr[:-4]

array([0, 1])

In [81]:
arr2[:]

array([[40, 19,  5, 43, 56, 64,  8, 25, 82, 94],
       [34, 95, 52, 24,  0,  6,  4, 27, 46, 67],
       [50, 79, 90, 30, 49, 85, 41, 90, 97, 55],
       [13, 96, 66, 33, 95, 43, 61, 22, 42, 96],
       [24, 90, 57, 95, 90, 67, 95, 67,  4, 45],
       [84, 32, 49, 31, 16, 14, 68, 86, 30, 25],
       [ 6, 10, 82,  7, 17, 70,  4, 50, 85, 58],
       [28, 45, 43,  0, 17,  0, 25, 53, 19, 17],
       [ 5, 67, 88,  9,  4, 48, 89, 75,  2, 60],
       [34, 30, 88, 48,  8, 84, 84, 99, 69, 90]])

In [82]:
arr2[0:5]

array([[40, 19,  5, 43, 56, 64,  8, 25, 82, 94],
       [34, 95, 52, 24,  0,  6,  4, 27, 46, 67],
       [50, 79, 90, 30, 49, 85, 41, 90, 97, 55],
       [13, 96, 66, 33, 95, 43, 61, 22, 42, 96],
       [24, 90, 57, 95, 90, 67, 95, 67,  4, 45]])

In [83]:
arr2

array([[40, 19,  5, 43, 56, 64,  8, 25, 82, 94],
       [34, 95, 52, 24,  0,  6,  4, 27, 46, 67],
       [50, 79, 90, 30, 49, 85, 41, 90, 97, 55],
       [13, 96, 66, 33, 95, 43, 61, 22, 42, 96],
       [24, 90, 57, 95, 90, 67, 95, 67,  4, 45],
       [84, 32, 49, 31, 16, 14, 68, 86, 30, 25],
       [ 6, 10, 82,  7, 17, 70,  4, 50, 85, 58],
       [28, 45, 43,  0, 17,  0, 25, 53, 19, 17],
       [ 5, 67, 88,  9,  4, 48, 89, 75,  2, 60],
       [34, 30, 88, 48,  8, 84, 84, 99, 69, 90]])

In [84]:
arr2[1,4]

0

In [85]:
arr2

array([[40, 19,  5, 43, 56, 64,  8, 25, 82, 94],
       [34, 95, 52, 24,  0,  6,  4, 27, 46, 67],
       [50, 79, 90, 30, 49, 85, 41, 90, 97, 55],
       [13, 96, 66, 33, 95, 43, 61, 22, 42, 96],
       [24, 90, 57, 95, 90, 67, 95, 67,  4, 45],
       [84, 32, 49, 31, 16, 14, 68, 86, 30, 25],
       [ 6, 10, 82,  7, 17, 70,  4, 50, 85, 58],
       [28, 45, 43,  0, 17,  0, 25, 53, 19, 17],
       [ 5, 67, 88,  9,  4, 48, 89, 75,  2, 60],
       [34, 30, 88, 48,  8, 84, 84, 99, 69, 90]])

In [86]:
arr2[5,-5]

14

In [87]:
arr2

array([[40, 19,  5, 43, 56, 64,  8, 25, 82, 94],
       [34, 95, 52, 24,  0,  6,  4, 27, 46, 67],
       [50, 79, 90, 30, 49, 85, 41, 90, 97, 55],
       [13, 96, 66, 33, 95, 43, 61, 22, 42, 96],
       [24, 90, 57, 95, 90, 67, 95, 67,  4, 45],
       [84, 32, 49, 31, 16, 14, 68, 86, 30, 25],
       [ 6, 10, 82,  7, 17, 70,  4, 50, 85, 58],
       [28, 45, 43,  0, 17,  0, 25, 53, 19, 17],
       [ 5, 67, 88,  9,  4, 48, 89, 75,  2, 60],
       [34, 30, 88, 48,  8, 84, 84, 99, 69, 90]])

In [88]:
arr2[-1,-2]

69

In [89]:
arr2[::-1]

array([[34, 30, 88, 48,  8, 84, 84, 99, 69, 90],
       [ 5, 67, 88,  9,  4, 48, 89, 75,  2, 60],
       [28, 45, 43,  0, 17,  0, 25, 53, 19, 17],
       [ 6, 10, 82,  7, 17, 70,  4, 50, 85, 58],
       [84, 32, 49, 31, 16, 14, 68, 86, 30, 25],
       [24, 90, 57, 95, 90, 67, 95, 67,  4, 45],
       [13, 96, 66, 33, 95, 43, 61, 22, 42, 96],
       [50, 79, 90, 30, 49, 85, 41, 90, 97, 55],
       [34, 95, 52, 24,  0,  6,  4, 27, 46, 67],
       [40, 19,  5, 43, 56, 64,  8, 25, 82, 94]])

Thiss  Slicing willl revverse the array

In [90]:
arr2[::-2]

array([[34, 30, 88, 48,  8, 84, 84, 99, 69, 90],
       [28, 45, 43,  0, 17,  0, 25, 53, 19, 17],
       [84, 32, 49, 31, 16, 14, 68, 86, 30, 25],
       [13, 96, 66, 33, 95, 43, 61, 22, 42, 96],
       [34, 95, 52, 24,  0,  6,  4, 27, 46, 67]])

This will print the alternate row from down side or backward

In [91]:
arr2[::-3]

array([[34, 30, 88, 48,  8, 84, 84, 99, 69, 90],
       [ 6, 10, 82,  7, 17, 70,  4, 50, 85, 58],
       [13, 96, 66, 33, 95, 43, 61, 22, 42, 96],
       [40, 19,  5, 43, 56, 64,  8, 25, 82, 94]])

This will print the every third row from backward

In [92]:
arr2[:-3]

array([[40, 19,  5, 43, 56, 64,  8, 25, 82, 94],
       [34, 95, 52, 24,  0,  6,  4, 27, 46, 67],
       [50, 79, 90, 30, 49, 85, 41, 90, 97, 55],
       [13, 96, 66, 33, 95, 43, 61, 22, 42, 96],
       [24, 90, 57, 95, 90, 67, 95, 67,  4, 45],
       [84, 32, 49, 31, 16, 14, 68, 86, 30, 25],
       [ 6, 10, 82,  7, 17, 70,  4, 50, 85, 58]])

In [93]:
arr

array([0, 1, 2, 3, 4, 5])

In [94]:
arr.max()

5

In [95]:
arr.min()

0

In [96]:
arr.mean()

2.5

In [97]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [98]:
from numpy import *

In [99]:
a = array([1,2,3,4,6])

In [100]:
median(a)

3.0

# Reshape

In [101]:
arr

array([0, 1, 2, 3, 4, 5])

In [102]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [103]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [104]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [105]:
arr

array([0, 1, 2, 3, 4, 5])

In [106]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [107]:
arr

array([0, 1, 2, 3, 4, 5])

In [108]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [109]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [110]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [111]:
arr

array([0, 1, 2, 3, 4, 5])

In [112]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [113]:
arr.reshape(4,1)

ValueError: cannot reshape array of size 6 into shape (4,1)

In [114]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

# Indexing

In [115]:
mat = np.arange(0,100).reshape(10,10)

In [116]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
row = 4

In [118]:
col = 5

In [119]:
row

4

In [120]:
col

5

In [121]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
mat[row,col]

45

In [123]:
mat[4,5]

45

In [124]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [125]:
col =  6

In [126]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [127]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [128]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [129]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [130]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [132]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [133]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [134]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [135]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [137]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [138]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [139]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [140]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [141]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [142]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [143]:
mat[0,1]

1

In [144]:
mat[1,6]

16

In [145]:
mat[3,5]

35

In [146]:
mat[2:3,2:3]

array([[22]])

In [147]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [148]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [149]:
mat[2:3,4:5]

array([[24]])

# Masking

In [150]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [151]:
id(mat)

2588435470576

In [152]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [153]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [154]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [155]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [156]:
mat[mat==50]

array([50])

In [157]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [159]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [160]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [163]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [165]:
a4 = mat[mat==50]
a4

array([50])

In [193]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

otp_length = 6  
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 005245


In [194]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [195]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [196]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000025AAAD0D640>


In [197]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
